services:
  redis:
    image: redis:latest
    networks:
      - backend

  vote:
    image: docker/example-voting-app-vote:latest
    ports:
      - 5000:80
    networks:
      - frontend
      - backend
    depends_on:
      - redis

  db:
    image: postgres:9.4
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - backend

  worker:
    image: docker/example-voting-app-worker
    networks:
      - backend
    depends_on:
      - db

  result:
    image: docker/example-voting-app-result
    networks:
      - frontend
      - backend
    ports:
      - 5001:80
    depends_on:
      - db
      - worker

networks:
  frontend:
  backend: