apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: db
    tier: backend
status:
  loadBalancer: {}
---
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: db
    tier: backend
  name: db
spec:
  containers:
  - env:
    - name: POSTGRES_HOST_AUTH_METHOD
      value: trust
    image: postgres:9.4
    name: db
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5432
    resources: {}
    livenessProbe:
      tcpSocket:
        port: 5432
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: tier
            operator: In
            values:
            - frontend
        topologyKey: kubernetes.io/hostname
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: tier
              operator: In
              values:
              - backend
            - key: app
              operator: In
              values:
              - redis
          topologyKey: kubernetes.io/hostname
status: {}
