apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    run: db
status:
  loadBalancer: {}
---
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: db
  name: db
spec:
  containers:
  - env:
    - name: POSTGRES_HOST_AUTH_METHOD
      value: trust
    image: postgres:9.4
    name: db
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5432
    resources: {}
    livenessProbe:
      tcpSocket:
        port: 5432
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}