apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: result
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: result
status:
  loadBalancer: {}
---
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: result
  name: result
spec:
  containers:
  - image: docker/example-voting-app-result
    name: result
    ports:
    - containerPort: 80
    resources: {}
    livenessProbe:
      httpGet:
        path: /
        port: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
