apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: vote
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: vote
status:
  loadBalancer: {}
---
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: vote
  name: vote
spec:
  containers:
  - image: docker/example-voting-app-vote
    name: vote
    ports:
    - containerPort: 80
    resources: {}
    readinessProbe:
      exec:
        command:
        - 'nc'
        - '-z'
        - 'redis.default.svc.cluster.local'
        - '6379'
      initialDelaySeconds: 5
      failureThreshold: 5
      timeoutSeconds: 10
    livenessProbe:
      httpGet:
        path: /
        port: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}