apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: worker
  name: worker
spec:
  containers:
  - image: docker/example-voting-app-worker
    name: worker
    resources: {}
    imagePullPolicy: IfNotPresent
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
