apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-db
  name: db
spec:
  type: ClusterIP
  ports:
  - name: {{ .Release.Name }}-db-svc
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
  selector:
    app: {{ .Release.Name }}-db
  
