apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploment
  labels:
    tier: frontend
    app: nginx
spec:
  selector:
    matchLabels:
      tier: frontend
  replicas: 3
  template:
    metadata:
      name: nginx-2
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
