apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-deploy-dev
  name: web-deploy-dev
  namespace: dev
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web-deploy-dev
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-deploy-dev
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            cpu: 0.5m
            memory: 250Mi
          limits:
            cpu: 1
            memory: 500Mi
status: {}
