apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: vote
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: vote
    tier: frontend
status:
  loadBalancer: {}
---
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: vote
    tier: frontend
  name: vote
spec:
  containers:
  - image: docker/example-voting-app-vote
    name: vote
    ports:
    - containerPort: 80
    resources: {}
    readinessProbe:
      exec:
        command:
        - 'nc'
        - '-z'
        - 'redis.default.svc.cluster.local'
        - '6379'
      initialDelaySeconds: 5
      failureThreshold: 5
      timeoutSeconds: 10
    livenessProbe:
      httpGet:
        path: /
        port: 80
    resources:
      requests:
        cpu: 2
        memory: 250Mi
      limits:
        cpu: 2
        memory: 500Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: tier
            operator: In
            values:
            - premium
            - performance
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: tier
            operator: In
            values:
            - backend
        topologyKey: kubernetes.io/hostname
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - result
            - key: tier
              operator: In
              values:
              - frontend
          topologyKey: kubernetes.io/hostname
status: {}
