apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-redis
  name: redis
spec:
  type: ClusterIP
  ports:
  - name: {{ .Release.Name }}-redis-svc
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
  selector:
    app: {{ .Release.Name }}-redis
  
